export const content = {
  en: {
    nav: {
      about: "About",
      work: "Work",
      experience: "Experience",
      skills: "Skills",
      contact: "Contact",
      downloadCV: "Download CV",
    },
    hero: {
      badge: "Open to work — Surakarta & remote",
      headline1: "I build",
      headlineAccent: "data systems",
      headline2: "that ship to production.",
      sub: "Economics grad (3.85, Cum Laude) turned full-stack analyst. I ship end-to-end products — Next.js + Supabase dashboards, Python data pipelines, Tableau reporting — for real organisations, not toy demos. Currently building the national sales pipeline at PT Intan Pariwara.",
      cta1: "See selected work",
      cta2: "Get in touch",
    },
    stats: [
      { value: 3.85, decimals: 2, unit: "/4.00", label: "GPA", context: "Cum Laude, Universitas Negeri Malang" },
      { value: 514, decimals: 0, unit: "", label: "Districts covered", context: "SIRUP scraper, all 514 kabupaten/kota" },
      { value: 3, decimals: 0, unit: "", label: "Internships shipped", context: "Intan Pariwara · Pintar.co · Telkomsel" },
      { value: 2, decimals: 0, unit: "", label: "Systems adopted", context: "NSMS + Warehouse Dashboard in production use" },
    ],
    projects: {
      sectionLabel: "Selected work",
      sectionTitle: "Three systems, all shipped to",
      sectionAccent: "real teams",
      sectionSub: "Each project started from a real operational problem and was adopted (or is being adopted) as the primary tool — not a portfolio exercise. Stack, role, and outcome below.",
      items: [
        {
          title: "National Sales Management System",
          division: "KLDI Division",
          impact: "Adopted by management",
          description: "Full-stack production CRM rebuilt from an HTML prototype. Real-time pipeline tracking, role-based views, and KPI dashboards for the national sales team. Currently the primary management monitoring tool.",
          liveLabel: "Live",
          githubLabel: "GitHub",
        },
        {
          title: "Government Procurement Pipeline",
          division: "Solo engineer",
          impact: "514 districts indexed",
          description: "Python scraper covering every kabupaten/kota in Indonesia, with session auth, anti-fail resume, and DuckDB analysis. Powers lead scoring and national market sizing at Intan Pariwara — a process that previously took weeks of manual research.",
          liveLabel: "Internal",
          githubLabel: "GitHub",
        },
        {
          title: "Warehouse Fulfillment Dashboard",
          division: "Jombang",
          impact: "Hybrid model · Rp 169 M/mo",
          description: "Prototype for a hybrid fulfilment model — passive rental + activity-based billing. Implements dead-stock fees, SKU tiering, and auto-billing across 6 modules including a visual pallet-grid warehouse map.",
          liveLabel: "Live",
          githubLabel: "GitHub",
        },
      ],
    },
    experience: {
      sectionLabel: "Experience",
      sectionTitle: "Three internships, one degree,",
      sectionAccent: "one through-line",
      sectionSub: "data that ships.",
      items: [
        {
          role: "Business Intelligence & Marketing Support Intern",
          location: "Klaten · Central Java",
          period: "Jan 2026 – Present",
          bullets: [
            "Designed, built, and deployed a full-stack Sales Funnel CRM (Next.js + Supabase + Vercel) — adopted as the primary management monitoring tool across the national sales team.",
            "Engineered an automated Python pipeline to collect SIRUP procurement data across all 514 districts, enabling national-scale market sizing and lead scoring.",
            "Built Power BI / Tableau dashboards for competitor benchmarking; findings incorporated into strategic planning.",
          ],
        },
        {
          role: "Business Intelligence Intern",
          location: "MSIB Batch 6 · Remote",
          period: "Feb – Jun 2024",
          bullets: [
            "End-to-end SQL analysis on large consumer datasets (joins, CTEs, window functions) — defined KPI logic and built reporting infrastructure for senior leadership.",
            "Shipped real-time Tableau dashboards tracking user behaviour across product and growth functions; presented findings directly to leadership.",
            "Collaborated cross-functionally with product, engineering, and business teams to align analytics with operational needs.",
          ],
        },
        {
          role: "Youth Digital Administrator Intern",
          location: "Surakarta",
          period: "Jan – May 2024",
          bullets: [
            "Monitored compliance and tracked performance metrics for 70 program participants; escalated corrective strategies to management.",
            "Managed high-volume daily transaction records in Excel; maintained audit-ready documentation.",
            "Delivered weekly analytics reports enabling timely regional strategy adjustments.",
          ],
        },
        {
          role: "B.Sc. Economic Development",
          location: "GPA 3.85 · Cum Laude",
          period: "2021 – 2025",
          bullets: [
            "Thesis: VECM time-series modelling of macroeconomic transmission (interest rates, inflation, exchange rate dynamics) in EViews.",
            "Best Participant — BESS 2025 International Conference; co-authored research on digital software adoption using the TAM framework.",
            "Chief Executive of Indonesia Day 2023 — led 8 divisions, managed cross-functional budget allocation, delivered on schedule.",
          ],
        },
      ],
    },
    skills: {
      sectionLabel: "Skills",
      sectionTitle: "Technical fluency,",
      sectionAccent: "business fluency",
      sectionSub: "I read SQL and stakeholder emails with equal ease. The list below is what I reach for daily, not what I\u0027ve heard of.",
      technicalTitle: "Technical & data",
      businessTitle: "Business & domain",
      certificationsLabel: "Certifications",
    },
    contact: {
      eyebrow: "Get in touch",
      title: "Looking for someone who ships?",
      accent: "Let\u0027s talk.",
      sub: "Open to Data Analytics, Management Consulting, and Management Trainee positions. Available immediately — based in Surakarta, happy to relocate.",
      email: "Send email",
      linkedin: "LinkedIn",
      repliesWithin: "Replies within 24h",
    },
    footer: {
      built: "Built with Next.js & Framer Motion",
    },
  },
  id: {
    nav: {
      about: "Tentang",
      work: "Proyek",
      experience: "Pengalaman",
      skills: "Keahlian",
      contact: "Kontak",
      downloadCV: "Unduh CV",
    },
    hero: {
      badge: "Mencari kerja — Surakarta & remote",
      headline1: "Saya membangun",
      headlineAccent: "sistem data",
      headline2: "yang benar-benar dipakai.",
      sub: "Lulusan Ekonomi (3.85, Cum Laude) yang beralih menjadi analis full-stack. Saya membangun produk end-to-end — dashboard Next.js + Supabase, pipeline data Python, pelaporan Tableau — untuk organisasi nyata, bukan sekadar demo portofolio. Saat ini membangun pipeline penjualan nasional di PT Intan Pariwara.",
      cta1: "Lihat proyek pilihan",
      cta2: "Hubungi saya",
    },
    stats: [
      { value: 3.85, decimals: 2, unit: "/4.00", label: "IPK", context: "Cum Laude, Universitas Negeri Malang" },
      { value: 514, decimals: 0, unit: "", label: "Kabupaten/kota", context: "Scraper SIRUP mencakup seluruh Indonesia" },
      { value: 3, decimals: 0, unit: "", label: "Magang diselesaikan", context: "Intan Pariwara · Pintar.co · Telkomsel" },
      { value: 2, decimals: 0, unit: "", label: "Sistem diadopsi", context: "NSMS + Warehouse Dashboard dipakai produksi" },
    ],
    projects: {
      sectionLabel: "Proyek pilihan",
      sectionTitle: "Tiga sistem, semua dipakai oleh",
      sectionAccent: "tim nyata",
      sectionSub: "Setiap proyek berawal dari masalah operasional nyata dan diadopsi (atau sedang diadopsi) sebagai alat utama — bukan latihan portofolio.",
      items: [
        {
          title: "Sistem Manajemen Penjualan Nasional",
          division: "Divisi KLDI",
          impact: "Diadopsi manajemen",
          description: "CRM produksi full-stack yang dibangun ulang dari prototipe HTML. Pelacakan pipeline real-time, tampilan berbasis peran, dan dashboard KPI untuk tim penjualan nasional. Saat ini menjadi alat pemantauan utama manajemen.",
          liveLabel: "Live",
          githubLabel: "GitHub",
        },
        {
          title: "Pipeline Pengadaan Pemerintah",
          division: "Engineer tunggal",
          impact: "514 kabupaten/kota terindeks",
          description: "Scraper Python yang mencakup setiap kabupaten/kota di Indonesia, dengan autentikasi sesi, resume anti-gagal, dan analisis DuckDB. Mendukung lead scoring dan sizing pasar nasional di Intan Pariwara — proses yang sebelumnya memakan waktu berminggu-minggu riset manual.",
          liveLabel: "Internal",
          githubLabel: "GitHub",
        },
        {
          title: "Dashboard Fulfillment Gudang",
          division: "Jombang",
          impact: "Model hybrid · Rp 169 M/bln",
          description: "Prototipe model fulfilment hybrid — sewa pasif + tagihan berbasis aktivitas. Mengimplementasikan biaya dead-stock, tiering SKU, dan auto-billing di 6 modul termasuk peta gudang visual pallet-grid.",
          liveLabel: "Live",
          githubLabel: "GitHub",
        },
      ],
    },
    experience: {
      sectionLabel: "Pengalaman",
      sectionTitle: "Tiga magang, satu gelar,",
      sectionAccent: "satu benang merah",
      sectionSub: "data yang benar-benar dipakai.",
      items: [
        {
          role: "Intern Business Intelligence & Marketing Support",
          location: "Klaten · Jawa Tengah",
          period: "Jan 2026 – Sekarang",
          bullets: [
            "Merancang, membangun, dan men-deploy CRM Sales Funnel full-stack (Next.js + Supabase + Vercel) — diadopsi sebagai alat pemantauan manajemen utama di seluruh tim penjualan nasional.",
            "Membangun pipeline Python otomatis untuk mengumpulkan data pengadaan SIRUP di seluruh 514 kabupaten/kota, memungkinkan sizing pasar dan lead scoring skala nasional.",
            "Membuat dashboard Power BI / Tableau untuk benchmarking kompetitor; temuan dimasukkan ke dalam perencanaan strategis.",
          ],
        },
        {
          role: "Intern Business Intelligence",
          location: "MSIB Batch 6 · Remote",
          period: "Feb – Jun 2024",
          bullets: [
            "Analisis SQL end-to-end pada dataset konsumen besar (joins, CTEs, window functions) — mendefinisikan logika KPI dan membangun infrastruktur pelaporan untuk pimpinan senior.",
            "Men-deploy dashboard Tableau real-time yang melacak perilaku pengguna di fungsi produk dan pertumbuhan; mempresentasikan temuan langsung ke pimpinan.",
            "Berkolaborasi lintas fungsi dengan tim produk, engineering, dan bisnis untuk menyelaraskan analitik dengan kebutuhan operasional.",
          ],
        },
        {
          role: "Intern Administrator Digital Pemuda",
          location: "Surakarta",
          period: "Jan – Mei 2024",
          bullets: [
            "Memantau kepatuhan dan melacak metrik kinerja untuk 70 peserta program; mengeskalasi strategi korektif ke manajemen.",
            "Mengelola catatan transaksi harian bervolume tinggi di Excel; memelihara dokumentasi siap audit.",
            "Menyampaikan laporan analitik mingguan yang memungkinkan penyesuaian strategi regional tepat waktu.",
          ],
        },
        {
          role: "S1 Ekonomi Pembangunan",
          location: "IPK 3.85 · Cum Laude",
          period: "2021 – 2025",
          bullets: [
            "Skripsi: Pemodelan VECM time-series transmisi makroekonomi (suku bunga, inflasi, dinamika nilai tukar) di EViews.",
            "Peserta Terbaik — Konferensi Internasional BESS 2025; co-author riset adopsi software digital menggunakan framework TAM.",
            "Ketua Pelaksana Indonesia Day 2023 — memimpin 8 divisi, mengelola alokasi anggaran lintas fungsi, diselesaikan tepat waktu.",
          ],
        },
      ],
    },
    skills: {
      sectionLabel: "Keahlian",
      sectionTitle: "Mahir teknis,",
      sectionAccent: "mahir bisnis",
      sectionSub: "Saya membaca SQL dan email stakeholder dengan kemampuan yang sama. Daftar di bawah adalah yang saya gunakan sehari-hari, bukan sekadar yang pernah saya dengar.",
      technicalTitle: "Teknis & data",
      businessTitle: "Bisnis & domain",
      certificationsLabel: "Sertifikasi",
    },
    contact: {
      eyebrow: "Hubungi",
      title: "Mencari orang yang bisa deliver?",
      accent: "Mari bicara.",
      sub: "Terbuka untuk posisi Data Analytics, Management Consulting, dan Management Trainee. Tersedia segera — berbasis di Surakarta, siap relokasi.",
      email: "Kirim email",
      linkedin: "LinkedIn",
      repliesWithin: "Balas dalam 24 jam",
    },
    footer: {
      built: "Dibuat dengan Next.js & Framer Motion",
    },
  },
}
